config/routes.rb
Rails.application.routes.draw do
  get 'order/new'

  get 'order/create'

  get 'charges/new'

  get 'charges/create'

  get 'tester/show'

  resources :contact, only: [:create]
  resources :products, only: [:index]
  resource :cart, only: [:show]
  resources :order_items, only: [:create, :update, :destroy]
  resources :charges, only: [:new, :create]
  # root to: "products#index"

  get 'order_items/create'

  get 'order_items/update'

  get 'order_items/destroy'

  get 'carts/show'

   # resources :home

  get 'home/products'

  get 'home/about'

  get 'home/takeAction'

  get 'home/cart'

  get 'home/contact'

  get 'home/index'

  get 'home/faq'

  root 'home#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/order.rb
class Order < ApplicationRecord
  belongs_to :order_status
  has_many :order_items
  before_validation :set_order_status, on: :create
  before_save :update_subtotal

  def subtotal
    order_items.collect { |oi| oi.valid? ? (oi.quantity * oi.unit_price) : 0 }.sum
  end
private
  def set_order_status
    self.order_status_id = 1
  end

  def update_subtotal
    self[:subtotal] = subtotal
  end
end

app/models/order_item.rb
class OrderItem < ApplicationRecord
  belongs_to :product
  belongs_to :order

  validates :quantity, presence: true, numericality: { only_integer: true, greater_than: 0 }
  validate :product_present
  validate :order_present

  before_save :finalize #updates the unit_price and total_price fields


  def unit_price  #as long as item is in cart, item price will not change to protect the customer
    if persisted?
      self[:unit_price]
    else
      product.price
    end
  end

  def total_price
    unit_price * quantity
  end

  def increment_quantity
    self.quantity = self.quantity + 1
  end

private
  def product_present
    if product.nil?
      errors.add(:product, "is not valid or is not active.")
    end
  end

  def order_present
    if order.nil?
      errors.add(:order, "is not a valid order.")
    end
  end

  def finalize
    self[:unit_price] = unit_price
    self[:total_price] = quantity * self[:unit_price]
  end
end

app/models/order_status.rb
class OrderStatus < ApplicationRecord
  has_many :orders
end

app/models/product.rb
class Product < ApplicationRecord
  has_many :order_items

  default_scope { where(active: true) } #checks if active flag is set to true. Ensures that deleted/inactive products aren't shown
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  helper_method :current_order
  helper_method :current_order_total_quantity

  def current_order
    if !session[:order_id].nil?
      begin
        order_found = Order.find(session[:order_id])
        return order_found
        if order_found == nil
          Order.new
        else
          order_found
        end
      rescue ActiveRecord::RecordNotFound
        session.delete(:order_id)
        Order.new
      end
    else
      Order.new
    end
  end

  def current_order_total_quantity
      total_quantity = 0
      current_order.order_items.each do |order_item|
        total_quantity += order_item.quantity
      end
      total_quantity
  end
end

app/controllers/carts_controller.rb
class CartsController < ApplicationController
  def show
    @order_items = current_order.order_items
  end
end

app/controllers/charges_controller.rb
class ChargesController < ApplicationController
  def create
    @order = current_order

     # Creates a Stripe Customer object, for associating
     # with the charge
     customer = Stripe::Customer.create(
       :email => params[:stripeEmail],
       :source  => params[:stripeToken],
       :metadata => {:first_name => params[:firstname],
                    :last_name => params[:lastname],
                    :shippingaddress1 => params[:shippingaddress1],
                    :shippingaddress2 => params[:shippingaddress2],
                    :shippingcountry => "England",
                    :shippingcounty => params[:shippingcountry],
                    :shippingcity => params[:shippingcity],
                    :postcode => params[:postcode]}
     )
     begin
       # Where the real magic happens
       charge = Stripe::Charge.create(
         :customer    => customer.id,
         :amount      => (@order.subtotal * 100).to_i,
         :description => 'Rails Stripe customer',
         :currency    => 'usd',
         :receipt_email => customer.email,
       )
       flash[:notice] = "Thanks for your payment, #{params[:firstname]} #{params[:lastname]}! You will recieve an email shortly with your order confirmation."

       redirect_to root_path
       session.delete(:order_id)
     rescue Stripe::CardError => e
       flash[:alert] = e.message
       redirect_to new_charge_path
     end



   end

   def new
     @order = current_order
     @stripe_btn_data = {
       key: "#{ Rails.configuration.stripe[:publishable_key] }",
       description: "Cart price",
       amount: Amount.default
     }
   end
end

app/controllers/contact_controller.rb
class ContactController < ApplicationController
 skip_before_action :verify_authenticity_token

  def create
    name = params[:name]
    lastname = params[:surname]
    email = params[:email]
    phone = params[:phone]
    message = params[:message]
    ContactMailer.send_feedback_email(name, email, message).deliver_now
    redirect_to home_index_path, notice: 'Thank you for your feedback! We will respond shortly.'
  end

end

app/controllers/home_controller.rb
class HomeController < ApplicationController

  def index
    @current_page='index'
  end

  def faq
    @current_pages='faq'
  end

  def products
    @current_page='products'
  end

  def about
    @current_page='about'
  end

  def takeAction
    @current_page='takeAction'
  end

  def cart
    @current_page='cart'
  end

  def contact
    @current_page='contact'
  end
end

app/controllers/order_controller.rb
class OrderController < ApplicationController
  def new
    @order_items = current_order.order_items
    @order = current_order
  end

  def create
  end
end

app/controllers/order_items_controller.rb
class OrderItemsController < ApplicationController
  def create
    @order = current_order
    @order_item = @order.order_items.where(product_id: order_item_params[:product_id]).first

    if @order_item
      @order_item.quantity = @order_item.quantity + order_item_params[:quantity].to_i
    else
      @order_item = @order.order_items.new(order_item_params)
    end


    @order_item.save!
    @order.save
    # You have the ID
    # Load the product
    # Call product.name
    @product = Product.find(order_item_params[:product_id])
    @alert_text = @product.name
    session[:order_id] = @order.id
  end

  def update
    @order = current_order
    @order_item = @order.order_items.find(params[:id])
    @order_item.update_attributes(order_item_params)
    @order_items = @order.order_items
  end

  def destroy
    @order = current_order
    @order_item = @order.order_items.find(params[:id])
    @order_item.destroy
    @order_items = @order.order_items
  end

private
  def order_item_params
    params.require(:order_item).permit(:quantity, :product_id)
  end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  def index
    @products = Product.all
    @order_item = current_order.order_items.new
  end
end

app/controllers/tester_controller.rb
class TesterController < ApplicationController
  def show
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/carts_helper.rb
module CartsHelper
end

app/helpers/charges_helper.rb
module ChargesHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/order_helper.rb
module OrderHelper
end

app/helpers/order_items_helper.rb
module OrderItemsHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/carts/_cart_row.html.erb
<div class="well">

  <div class="row">
    <div class="col-xs-8">
      <h4><%= product.name %></h4>
    </div>
    <div class="col-xs-4">

      <%= form_for order_item, remote: true do |f| %>
        <h4 class="text-right">Unit Price: <span style="color: green"><%= number_to_currency order_item.unit_price %></span></h4>
        <div class="row">
          <div class="col-xs-4">
            <%= f.number_field :quantity, value: order_item.quantity.to_i, class: "form-control", min: 1 %>
            <%= f.hidden_field :product_id, value: product.id %>
          </div>
          <div class="col-xs-8 text-right">
            <div class="btn-group">
              <%= f.submit "Update Quantity", class: "btn btn-primary" %>
              <%= link_to "Delete", order_item, method: :delete, remote: true, class: "btn btn-danger" %>
            </div>
          </div>
        </div>
        <h4 class="text-right">Total Price: <span style="color: green"><%= number_to_currency order_item.total_price %></span></h4>
      <% end %>
    </div>

  </div>
</div>

app/views/carts/_shopping_cart.html.erb
<% if !@order_item.nil? && @order_item.errors.any? %>
  <div class="alert alert-danger">
    <ul>
    <% @order_item.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>
<% if @order_items.size == 0 %>
  <p class="text-center">
    There are no items in your shopping cart.  Please <%= link_to "go back", products_path %> and add some items to your cart.
  </p>
<% else %>
  <% @order_items.each do |order_item| %>
    <%= render 'carts/cart_row', product: order_item.product, order_item: order_item, show_total: true %>
  <% end %>
  <% number_to_currency current_order.subtotal %>
<% end %>

app/views/carts/_total.html.erb
<div class = "row">
  <div class = "col-sm">
    <h4 class="text-right"> Subtotal: <span style="color: purple"><%= number_to_currency current_order.subtotal %></span></h4>
  </div>
  <div class="col-sm">
    <%= link_to '<button type="button" class="btn btn-success pull-right">Proceed to Checkout</button>'.html_safe, order_new_path%>
  </div>
</div>

app/views/carts/show.html.erb
<div class="shopping-cart">
  <%= render "shopping_cart" %>
</div>

<%if current_order.subtotal == 0  %>
<div class = "row">
  <div class = "col-sm">
    <h4 class="text-right"> Subtotal: <span style="color: purple"><%= number_to_currency current_order.subtotal %></span></h4>
  </div>
  <div class="col-sm">
    <%= link_to '<button type="button" class="btn btn-success pull-right" disabled>Proceed to Checkout</button>'.html_safe, order_new_path%>
  </div>
</div>
<%else %>
<div class = "shopping-cart-total">
  <%= render "total" %>
</div>
<%end %>



<br>
<br>
<br>
<br>
<br>
<br>
<br>
<br>

app/views/charges/_shipping_info.html.erb
<!-- Richard says the below needs to be removed and put in head tag of application layout -->
<!-- <link href="//netdna.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap.min.css" rel="stylesheet" id="bootstrap-css">
<script src="//netdna.bootstrapcdn.com/bootstrap/3.2.0/js/bootstrap.min.js"></script>
<script src="//code.jquery.com/jquery-1.11.1.min.js"></script>
<script src="https://js.stripe.com/v2/"></script> -->
<!------ Include the above in your HEAD tag ---------->
<%= form_tag(charges_path, method: "post") do %>
  <div class="container">
	   <div class="row">
		     <img class="spi-header" src="" >
          <hr/>
          <h1>Where shall we ship your stickers?</h1>
          <hr/>
          <hr/>
          <h2 class="bg-success">Today's Total: <%= number_to_currency current_order.subtotal%></h2>

          <div class="form-group col-md-12 bg-primary">
              <label class="control-label" for="billinginformation">Shipping Information</label>
          </div>

          <div class="shipping-info">
              <div class="form-group col-md-6">
                <span class="required-lbl">* </span><label class="control-label" for="firstname">First Name</label>
                <div class="controls">
                  <input id="firstname" name="firstname" type="text" placeholder="" class="form-control" required="">
                </div>
              </div>

              <div class="form-group col-md-6">
                <span class="required-lbl">* </span><label class="control-label" for="lastname">Last Name</label>
                <div class="controls">
                  <input id="lastname" name="lastname" type="text" placeholder="" class="form-control" required="">
                </div>
              </div>

              <div class="form-group col-md-6">
                <span class="required-lbl">* </span><label class="control-label" for="shippingaddress1">Shipping Address 1</label>
                <div class="controls">
                  <input id="shippingaddress1" name="shippingaddress1" type="text" placeholder="" class="form-control" required="">
                </div>
              </div>

              <div class="form-group col-md-6">
                <label class="control-label" for="shippingaddress2">Shipping Address 2</label>
                <div class="controls">
                  <input id="shippingaddress2" name="shippingaddress2" type="text" placeholder="" class="form-control" required="">
                </div>
              </div>

              <div class="form-group col-md-6">
                <span class="required-lbl">* </span><label class="control-label" for="shippingcountry">Shipping Country</label>
                <div class="controls">
                   <div class="controls">
                      <select id="shippingcountry" name="shippingcountry" class="input-xlarge">
                        <option>Please Select</option>
                        <option>England</option>
                      </select>
                    </div>
                </div>
              </div>

               <div class="form-group col-md-6">
                <span class="required-lbl">* </span><label class="control-label" for="shippingstate">Shipping County</label>
                <div class="controls">
                  <select id="shippingstate" name="shippingstate" class="input-xlarge">
                    <option>Please Select</option>
                    <option>Bedfordshire</option>
                    <option>Berkshire</option>
                    <option>Bristol</option>
                    <option>Buckinghamshire</option>
                    <option>Cambridgeshire</option>
                    <option>Cheshire</option>
                    <option>Cornwall</option>
                    <option>County Durham</option>
                    <option>Cumberland</option>
                    <option>Derbyshire</option>
                    <option>Devon</option>
                    <option>Dorset</option>
                    <option>Essex</option>
                    <option>Gloucestershire</option>
                    <option>Hampshire</option>
                    <option>Herefordshire </option>
                    <option>Hertfordshire</option>
                    <option>Huntingdonshire</option>
                    <option>Kent</option>
                    <option>Lancashire</option>
                    <option>Leicestershire</option>
                    <option>Lincolnshire</option>
                    <option>Middlesex</option>
                    <option>Norfolk</option>
                    <option>Northamptonshire</option>
                    <option>Northumberland</option>
                    <option>Nottinghamshire</option>
                    <option>Oxfordshire</option>
                    <option>Rutland</option>
                    <option>Shropshire</option>
                    <option>Somerset</option>
                    <option>Staffordshire</option>
                    <option>Suffolk</option>
                    <option>Surrey</option>
                    <option>Sussex</option>
                    <option>Warwickshire</option>
                    <option>Westmorland</option>
                    <option>Wiltshire</option>
                    <option>Worcestershire</option>
                    <option>Yorkshire</option>

                  </select>
                </div>
              </div>

              <div class="form-group col-md-6">
                <span class="required-lbl">* </span><label class="control-label" for="shippingcity">Shipping City</label>
                <div class="controls">
                  <input id="shippingcity" name="shippingcity" type="text" placeholder="" class="form-control" required="">
                </div>
              </div>

              <div class="form-group col-md-6">
                <span class="required-lbl">* </span><label class="control-label" for="postcode">Post Code</label>
                <div class="controls">
                  <input id="postcode" name="postcode" type="text" placeholder="" class="form-control" required="">
                </div>
              </div>

              <hr/>


            </div>

            <script src="https://checkout.stripe.com/checkout.js" class="stripe-button"
              data-key="<%= Rails.configuration.stripe[:publishable_key] %>"
              data-description="Purchasing sticker(s)"
              data-amount="<%= current_order.subtotal * 100 %>"
              data-locale="auto"></script>
      </div>
	</div>
<% end %>

app/views/charges/_stripe_checkout.html.erb
<%= form_tag charges_path do %>
  <article>
    <% if flash[:error].present? %>
    <div id="error_explanation">
      <p><%= flash[:error] %></p>
    </div>
    <% end %>
    <label class="amount">
      <span>Amount: <%= number_to_currency current_order.subtotal %> </span>
    </label>
  </article>

  <script src="https://checkout.stripe.com/checkout.js" class="stripe-button"
    data-key="<%= Rails.configuration.stripe[:publishable_key] %>"
    data-description="Purchasing sticker(s)"
    data-amount="<%= current_order.subtotal * 100 %>"
    data-locale="auto"></script>
<% end %>

app/views/charges/create.html.erb
<h2>Cheers, you paid <%= number_to_currency(@order.subtotal) %>. You will receive an email with your order confirmation!</h2>

app/views/charges/new.html.erb
<%= form_tag charges_path do %>
  <h4>Click the button!</h4>
  <script class='stripe-button' src="https://checkout.stripe.com/checkout.js" data-key="<%= @stripe_btn_data[:key] %>" data-amount="<%= @stripe_btn_data[:amount] %>" data-description="<%= @stripe_btn_data[:description] %>" ></script>
<% end %>

app/views/home/about.html.erb
<h1>About DoorJunk.com</h1>
<p>"Sed ut perspiciatis unde omnis iste natus error sit voluptatem accusantium doloremque laudantium, totam rem aperiam, eaque ipsa quae ab illo inventore veritatis et quasi architecto beatae vitae dicta sunt explicabo. Nemo enim ipsam voluptatem quia voluptas sit aspernatur aut odit aut fugit, sed quia consequuntur magni dolores eos qui ratione voluptatem sequi nesciunt. Neque porro quisquam est, qui dolorem ipsum quia dolor sit amet, consectetur, adipisci velit, sed quia non numquam eius modi tempora incidunt ut labore et dolore magnam aliquam quaerat voluptatem. Ut enim ad minima veniam, quis nostrum exercitationem ullam corporis suscipit laboriosam, nisi ut aliquid ex ea commodi consequatur? Quis autem vel eum iure reprehenderit qui in ea voluptate velit esse quam nihil molestiae consequatur, vel illum qui dolorem eum fugiat quo voluptas nulla pariatur?"</p>

<div class="image">
  <%= image_tag "tarsier.jpg", height: "500", width: "700"%>
</div>

app/views/home/cart.html.erb
<div class="shopping-cart">
  <%= render :partial => "/carts/shopping_cart" %>
</div>

app/views/home/contact.html.erb
<h1>Comments? Questions? Suggestions?</h1>
<h2>Contact Us!</h2>

<form id="contact-form" method="post" action="/contact" role="form">

  <div class="messages"></div>

  <div class="controls">

    <div class="row">
      <div class="col-md-6">
        <div class="form-group">
          <label for="form_name">Firstname *</label>
          <input id="form_name" type="text" name="name" class="form-control" placeholder="Please enter your first name *" required="required" data-error="Firstname is required.">
          <div class="help-block with-errors"></div>
        </div>
      </div>
      <div class="col-md-6">
        <div class="form-group">
          <label for="form_lastname">Lastname *</label>
          <input id="form_lastname" type="text" name="surname" class="form-control" placeholder="Please enter your last name *" required="required" data-error="Lastname is required.">
          <div class="help-block with-errors"></div>
        </div>
      </div>
    </div>
    <div class="row">
      <div class="col-md-6">
        <div class="form-group">
          <label for="form_email">Email *</label>
          <input id="form_email" type="email" name="email" class="form-control" placeholder="Please enter your email *" required="required" data-error="Valid email is required.">
          <div class="help-block with-errors"></div>
        </div>
      </div>
      <div class="col-md-6">
        <div class="form-group">
          <label for="form_phone">Phone</label>
          <input id="form_phone" type="tel" name="phone" class="form-control" placeholder="Please enter your phone">
          <div class="help-block with-errors"></div>
        </div>
      </div>
    </div>
    <div class="row">
      <div class="col-md-12">
        <div class="form-group">
          <label for="form_message">Message *</label>
          <textarea id="form_message" name="message" class="form-control" placeholder="Write your message here *" rows="4" required="required" data-error="Please,leave us a message."></textarea>
          <div class="help-block with-errors"></div>
        </div>
      </div>
      <div class="col-md-12">
        <input type="submit" class="btn btn-success btn-send" value="Send message">
      </div>
    </div>
    <div class="row">
      <div class="col-md-12">
        <p class="text-muted">
      </div>
    </div>
  </div>

</form>

app/views/home/faq.html.erb
<h1>This page is in progress....stay tuned</h1>

app/views/home/index.html.erb
<body>
  <h1 class="hometile">Junk Mail is a Problem in the UK</h1>
  <p>NEARLY ALL UK HOUSEHOLDS RECEIVE POST (AND JUNK MAIL) THROUGH THE DOOR. THE LETTERBOX CONSTANTLY CLANGS WITH THE ARRIVAL OF USELESS AND WASTEFUL PAPER THAT FILLS OUR HOMES.</p>

  <h1 class="hometile">The (Only Available) Answer...?</h1>

  <p>PUT A MEAN SIGN ON YOUR LETTERBOX, THE TYPE COMMONLY RESERVED FOR THE ELDERLY, AND OPENLY UPTIGHT.</p>

  <h1 class="hometile">The Opportunity</h1>
  <p>COMBAT THIS PROBLEM THROUGH HUMOUR, ADDING JOY TO ONE’S HOME AND THE NEIGHBOURHOOD, AND STARTING A MOVEMENT TO RID THE WORLD OF JUNK MAIL FOR GOOD.</p>

  <div id="myCarousel" class="carousel slide" data-ride="carousel">
    <!-- Indicators -->
    <ol class="carousel-indicators">
      <li data-target="#myCarousel" data-slide-to="0" class="active"></li>
      <li data-target="#myCarousel" data-slide-to="1"></li>
      <li data-target="#myCarousel" data-slide-to="2"></li>
    </ol>

    <!-- Wrapper for slides -->
    <div class="carousel-inner">
      <div class="item active">
        <%= link_to(image_tag("sauim-de-coleira.jpg",  :href => "google.com", alt: "First Slide", class: "d-block w-100", width: 1200, height: 500), home_products_path) %>
      </div>

      <div class="item">
        <%= link_to(image_tag("tarsier.jpg",  alt: "First Slide", class: "d-block w-100", width: 1200, height: 500), home_products_path) %>
      </div>

      <div class="item">
        <%= link_to(image_tag("shutterstock.jpg",  alt: "First Slide", class: "d-block w-100",width: 1200, height: 500),home_products_path) %>
      </div>
    </div>

    <!-- Left and right controls -->
    <a class="left carousel-control" href="#myCarousel" data-slide="prev">
      <span class="glyphicon glyphicon-chevron-left"></span>
      <span class="sr-only">Previous</span>
    </a>
    <a class="right carousel-control" href="#myCarousel" data-slide="next">
      <span class="glyphicon glyphicon-chevron-right"></span>
      <span class="sr-only">Next</span>
    </a>
  </div>
</body>

app/views/home/takeAction.html.erb
<h1>Take Action</h1>
<p>This page is in progress. Stay tuned. </p>

app/views/order/_cart_row.html.erb
<div class="well">

  <div class="row">
    <div class="col-xs-8">
      <h4><%= product.name %></h4>
    </div>
    <div class="col-xs-4">
      <h4 class="text-right">Quantity: <span style="color: green"><%= order_item.quantity %></span></h4>
      <%= form_for order_item, remote: true do |f| %>
        <h4 class="text-right">Unit Price: <span style="color: green"><%= number_to_currency order_item.unit_price %></span></h4>
        <h4 class="text-right">Total Price: <span style="color: green"><%= number_to_currency order_item.total_price %></span></h4>
      <% end %>
    </div>

  </div>
</div>

app/views/order/_shopping_cart.html.erb
<% if !@order_item.nil? && @order_item.errors.any? %>
  <div class="alert alert-danger">
    <ul>
    <% @order_item.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>
<% if @order_items.size == 0 %>
  <p class="text-center">
    There are no items in your shopping cart.  Please <%= link_to "go back", products_path %> and add some items to your cart.
  </p>
<% else %>
  <% @order_items.each do |order_item| %>
    <%= render 'order/cart_row', product: order_item.product, order_item: order_item, show_total: true %>
  <% end %>
  <% number_to_currency current_order.subtotal %>
<% end %>

app/views/order/_total.html.erb
<div class = "row">
  <div class = "col-sm">
    <h4 class="text-right"> Subtotal: <span style="color: purple"><%= number_to_currency current_order.subtotal %></span></h4>
  </div>
  <div class="col-sm">
    <%= link_to '<button type="button" class="btn btn-success pull-right">Proceed to Checkout</button>'.html_safe, order_new_path%>
  </div>
</div>

app/views/order/create.html.erb
<%= render "charges/stripe_checkout" %>

app/views/order/new.html.erb
<h1>Order Summary</h1>
<%= render "shopping_cart" %>
<div class = "shopping-cart-total">
  <div class = "row">
    <div class = "col-sm">
      <h4 class="text-right"> Subtotal: <span style="color: purple"><%= number_to_currency current_order.subtotal %></span></h4>
    </div>
  </div>
</div>

<%= render "charges/shipping_info" %>

app/views/order_items/create.html.erb
<h1>OrderItems#create</h1>
<p>Find me in app/views/order_items/create.html.erb</p>

app/views/order_items/create.js.erb
<% if @order.errors.any? || @order_item.errors.any? %>
alert("not valid.")
<% else %>
  $(".cart-text").html("<%= escape_javascript(render 'layouts/cart_text') %>")
<% end %>

app/views/order_items/destroy.html.erb
<h1>OrderItems#destroy</h1>
<p>Find me in app/views/order_items/destroy.html.erb</p>

app/views/order_items/destroy.js.erb
$(".cart-text").html("<%= escape_javascript(render 'layouts/cart_text') %>")
$(".shopping-cart").html("<%= escape_javascript(render 'carts/shopping_cart') %>")
$(".shopping-cart-total").html("<%= escape_javascript(render 'carts/total') %>")

app/views/order_items/update.html.erb
<h1>OrderItems#update</h1>
<p>Find me in app/views/order_items/update.html.erb</p>

app/views/order_items/update.js.erb
$(".cart-text").html("<%= escape_javascript(render 'layouts/cart_text') %>")
$(".shopping-cart").html("<%= escape_javascript(render 'carts/shopping_cart') %>")

app/views/products/_product_row.html.erb
<div class="well">

  <div class="row">
    <div class="col-xs-8">
      <h4><%= product.name %></small></h4>
    </div>
    <div class="col-xs-4">

      <%= form_for order_item, remote: true do |f| %>
      <h4 class="text-right">Unit Price: <span style="color: green"><%= number_to_currency product.price %></span></h4>
        <div class="input-group">
          <%= f.number_field :quantity, value: 1, class: "form-control", min: 1 %>
          <div class="input-group-btn">
            <%= f.hidden_field :product_id, value: product.id %>
            <%= f.submit "Add to Cart", class: "btn btn-primary"%>
          </div>
        </div>
      <% end %>
    </div>

  </div>
</div>

app/views/products/index.html.erb
<div class="container">
  <div class="row">
    <div class="col-xs-6 pull-right">
      <h1 class="cart-text"><%= render 'layouts/cart_text' %></h1>
    </div>
  </div>
  <h3 class="text-center">Products for Sale</h3>

  <div class="row">
    <div class="col-xs-6 col-xs-offset-3">
      <% @products.each do |product| %>
        <%= render "product_row", product: product, order_item: @order_item %>
      <% end %>
    </div>
  </div>
</div>