config/routes.rb
Rails.application.routes.draw do
  get 'order/new'

  get 'order/create'

  get 'charges/new'

  get 'charges/create'

  get 'tester/show'

  resources :contact, only: [:create]
  resources :products, only: [:index]
  resource :cart, only: [:show]
  resources :order_items, only: [:create, :update, :destroy]
  resources :charges, only: [:new, :create]
  # root to: "products#index"

  get 'order_items/create'

  get 'order_items/update'

  get 'order_items/destroy'

  get 'carts/show'

   # resources :home

  get 'home/products'

  get 'home/about'

  get 'home/takeAction'

  get 'home/cart'

  get 'home/contact'

  get 'home/index'

  get 'home/faq'

  root 'home#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/order.rb
class Order < ApplicationRecord
  belongs_to :order_status
  has_many :order_items
  before_validation :set_order_status, on: :create
  before_save :update_subtotal

  def subtotal
    order_items.collect { |oi| oi.valid? ? (oi.quantity * oi.unit_price) : 0 }.sum
  end
private
  def set_order_status
    self.order_status_id = 1
  end

  def update_subtotal
    self[:subtotal] = subtotal
  end
end

app/models/order_item.rb
class OrderItem < ApplicationRecord
  belongs_to :product
  belongs_to :order

  validates :quantity, presence: true, numericality: { only_integer: true, greater_than: 0 }
  validate :product_present
  validate :order_present

  before_save :finalize #updates the unit_price and total_price fields


  def unit_price  #as long as item is in cart, item price will not change to protect the customer
    if persisted?
      self[:unit_price]
    else
      product.price
    end
  end

  def total_price
    unit_price * quantity
  end

  def increment_quantity
    self.quantity = self.quantity + 1
  end

private
  def product_present
    if product.nil?
      errors.add(:product, "is not valid or is not active.")
    end
  end

  def order_present
    if order.nil?
      errors.add(:order, "is not a valid order.")
    end
  end

  def finalize
    self[:unit_price] = unit_price
    self[:total_price] = quantity * self[:unit_price]
  end
end

app/models/order_status.rb
class OrderStatus < ApplicationRecord
  has_many :orders
end

app/models/product.rb
class Product < ApplicationRecord
  has_many :order_items

  default_scope { where(active: true) } #checks if active flag is set to true. Ensures that deleted/inactive products aren't shown
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  helper_method :current_order
  helper_method :current_order_total_quantity

  def current_order
    if !session[:order_id].nil?
      begin
        order_found = Order.find(session[:order_id])
        return order_found
        if order_found == nil
          Order.new
        else
          order_found
        end
      rescue ActiveRecord::RecordNotFound
        session.delete(:order_id)
        Order.new
      end
    else
      Order.new
    end
  end

  def current_order_total_quantity
      total_quantity = 0
      current_order.order_items.each do |order_item|
        total_quantity += order_item.quantity
      end
      total_quantity
  end
end

app/controllers/carts_controller.rb
class CartsController < ApplicationController
  def show
    @order_items = current_order.order_items
  end
end

app/controllers/charges_controller.rb
class ChargesController < ApplicationController
  def create
    @order = current_order

     # Creates a Stripe Customer object, for associating
     # with the charge
     customer = Stripe::Customer.create(
       :email => params[:stripeEmail],
       :source  => params[:stripeToken],
       :metadata => {:first_name => params[:firstname],
                    :last_name => params[:lastname],
                    :shippingaddress1 => params[:shippingaddress1],
                    :shippingaddress2 => params[:shippingaddress2],
                    :shippingcountry => "England",
                    :shippingcounty => params[:shippingcountry],
                    :shippingcity => params[:shippingcity],
                    :postcode => params[:postcode]}
     )
     begin
       # Where the real magic happens
       charge = Stripe::Charge.create(
         :customer    => customer.id,
         :amount      => (@order.subtotal * 100).to_i,
         :description => 'Rails Stripe customer',
         :currency    => 'usd',
         :receipt_email => customer.email,
       )
       flash[:notice] = "Thanks for your payment, #{params[:firstname]} #{params[:lastname]}! You will recieve an email shortly with your order confirmation."

       redirect_to root_path
       session.delete(:order_id)
     rescue Stripe::CardError => e
       flash[:alert] = e.message
       redirect_to new_charge_path
     end



   end

   def new
     @order = current_order
     @stripe_btn_data = {
       key: "#{ Rails.configuration.stripe[:publishable_key] }",
       description: "Cart price",
       amount: Amount.default
     }
   end
end

app/controllers/contact_controller.rb
class ContactController < ApplicationController
 skip_before_action :verify_authenticity_token

  def create
    name = params[:name]
    lastname = params[:surname]
    email = params[:email]
    phone = params[:phone]
    message = params[:message]
    ContactMailer.send_feedback_email(name, email, message).deliver_now
    redirect_to home_index_path, notice: 'Thank you for your feedback! We will respond shortly.'
  end

end

app/controllers/home_controller.rb
class HomeController < ApplicationController

  def index
    @current_page='index'
  end

  def faq
    @current_pages='faq'
  end

  def products
    @current_page='products'
  end

  def about
    @current_page='about'
  end

  def takeAction
    @current_page='takeAction'
  end

  def cart
    @current_page='cart'
  end

  def contact
    @current_page='contact'
  end
end

app/controllers/order_controller.rb
class OrderController < ApplicationController
  def new
    @order_items = current_order.order_items
    @order = current_order
  end

  def create
  end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  def index
    @products = Product.all
    @order_item = current_order.order_items.new
  end
end

app/controllers/tester_controller.rb
class TesterController < ApplicationController
  def show
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/carts_helper.rb
module CartsHelper
end

app/helpers/charges_helper.rb
module ChargesHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/order_helper.rb
module OrderHelper
end

app/helpers/order_items_helper.rb
module OrderItemsHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/layouts/_cart_text.html.erb
<%= link_to "#{current_order_total_quantity} Items in Cart ( #{number_to_currency current_order.subtotal} )", cart_path, class: "btn btn-link" %>
<% if @alert_text %>
  </br><small>Added <%=@alert_text%> to cart!</small>
<% else %>
</br><small>&nbsp</small>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Doorjunk</title>
    <%= csrf_meta_tags %>

    <meta name="viewport" content="width=device-width, initial-scale=1">

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div class="container">
    <nav class="navbar navbar-inverse">
      <div class="container-fluid">
        <div class="navbar-header">
          <a class="navbar-brand" href="<%= home_index_path %>">DoorJunk.com</a>
        </div>
        <ul class="nav navbar-nav">
          <li class="<%= @current_page === 'index' ? 'active' : '' %>" ><%= link_to "Home", home_index_path %></li>
          <li class="<%= @current_page === 'products' ? 'active' : '' %>" ><%= link_to "Products", products_path %></li>
          <li class="<%= @current_page === 'about' ? 'active' : '' %>" ><%= link_to "About", home_about_path %></li>
          <li class="<%= @current_page === 'takeAction' ? 'active' : '' %>" ><%= link_to "Take Action", home_takeAction_path %></li>
          <li class="<%= @current_page === 'faq' ? 'active' : '' %>" ><%= link_to "FAQ", home_faq_path %></li>
          <li class="<%= @current_page === 'contact' ? 'active' : '' %>" ><%= link_to "Contact", home_contact_path %></li>
          <li class="<%= @current_page === 'cart' ? 'active' : '' %>" ><%= link_to "Cart", cart_path %></li>
        </ul>
      </div>
      <% if flash[:notice] %>
        <div class="alert alert-info">
          <button type="button" class="close" data-dismiss="alert">&times;</button>
          <%= flash[:notice] %>
        </div>
    <% end -%>
    </nav>
      <%= yield %>
    </div>
  </body>
</html>